# Icons Makefile, PH May 2015

### Generate png icons from png
icons: icon.svg
	inkscape --file=icon.svg  --export-png=icon-16.png -w=16 -h=16
	inkscape --file=icon.svg  --export-png=icon-48.png -w=48 -h=48
	inkscape --file=icon.svg  --export-png=icon-60.png -w=60 -h=60
	inkscape --file=icon.svg  --export-png=icon-128.png -w=128 -h=128
