# Icons Makefile, PH May 2015

### Generate png icons from png
icons: bell.svg bell-active.svg
	inkscape --file=bell.svg  --export-png=bell-128.png -w=128 -h=128
	inkscape --file=bell-active.svg  --export-png=bell-active-128.png -w=128 -h=128
